---
#
# https://github.com/elastic/elasticsearch/blob/master/distribution/docker/src/docker/config/elasticsearch.yml
#

#
# CONFIG for cluster node "es02"
#

# common cluster config
network.host: 0.0.0.0
cluster.name: "elk-cluster"
cluster.initial_master_nodes: es01,es02,es03
bootstrap.memory_lock: true
path.repo: /usr/share/elasticsearch/snapshots

# node specific custom config
node.name: es02
discovery.seed_hosts: es01,es03

#
# X-Pack settings
# see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
#
xpack.security.enabled: true
xpack.license.self_generated.type: trial
xpack.monitoring.collection.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certificates/es02/es02.key
xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/certificates/ca/ca.crt
xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certificates/es02/es02.crt
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/certificates/ca/ca.crt
xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certificates/es02/es02.crt
xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certificates/es02/es02.key



