version: '3.2'

services:
  es01:
    container_name: es01
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/es01.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /mnt/volume-elastic-snapshots/data:/usr/share/elasticsearch/snapshots:rw
      #- es01-data:/usr/share/elasticsearch/data
      - /mnt/volume-elastic-data/es01-data:/usr/share/elasticsearch/data
      - es-certs:$CERTS_DIR
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - edelweiss_net
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=9200'
      - 'traefik.protocol=https'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.frontend.rule=Host:elastic.banovo.cloud'

  es02:
    container_name: es02
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/es02.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /mnt/volume-elastic-snapshots/data:/usr/share/elasticsearch/snapshots:rw
      #- es02-data:/usr/share/elasticsearch/data
      - /mnt/volume-elastic-data/es02-data:/usr/share/elasticsearch/data
      - es-certs:$CERTS_DIR
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    networks:
      - edelweiss_net
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=9200'
      - 'traefik.protocol=https'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.frontend.rule=Host:elastic-02.banovo.cloud'

  es03:
    container_name: es03
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/es03.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /mnt/volume-elastic-snapshots/data:/usr/share/elasticsearch/snapshots:rw
      #- es03-data:/usr/share/elasticsearch/data
      - /mnt/volume-elastic-data/es03-data:/usr/share/elasticsearch/data
      - es-certs:$CERTS_DIR
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    networks:
      - edelweiss_net
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=9200'
      - 'traefik.protocol=https'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.frontend.rule=Host:elastic-03.banovo.cloud'

  wait_until_ready:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    command: /usr/bin/true
    depends_on:
      - es01

  kibana:
    container_name: kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - es-certs:$CERTS_DIR
    depends_on:
      - es01
    networks:
      - edelweiss_net
    environment:
      - "ELASTICSEARCH_USERNAME=kibana_system"
      - "ELASTICSEARCH_PASSWORD=$KIBANA_PASSWORD"
      - "ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=${CERTS_DIR}/ca/ca.crt"
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=5601'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.frontend.rule=Host:kibana.banovo.cloud'

networks:
  edelweiss_net:
    external: true

volumes:
  es-certs:
  es01-data:
  es02-data:
  es03-data:
