version: '3.2'

services:
  es01:
    container_name: es01
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - es01-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=ncserver-es-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - entrypoint
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=9200'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.frontend.rule=Host:elastic-01.ncserver.cloud'

  es02:
    container_name: es02
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - es02-data:/usr/share/elasticsearch/data
    ports:
      - "9201:9201"
    environment:
      - node.name=es02
      - cluster.name=ncserver-es-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - entrypoint
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=9201'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.frontend.rule=Host:elastic-02.ncserver.cloud'

  es03:
    container_name: es03
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - es03-data:/usr/share/elasticsearch/data
    ports:
      - "9202:9202"
    environment:
      - node.name=es03
      - cluster.name=ncserver-es-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - entrypoint
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=9202'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.frontend.rule=Host:elastic-03.ncserver.cloud'

  logstash:
    container_name: logstash
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      # - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    networks:
      - entrypoint
    depends_on:
      - es01

  kibana:
    container_name: kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - es01
    ports:
      - "5601:5601"
    networks:
      - entrypoint
    environment:
      - "ELASTICSEARCH_URL=http://es01:9200"
      - "ELASTICSEARCH_HOSTS=http://es01:9200"
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=5601'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.frontend.rule=Host:kibana.ncserver.cloud'

networks:
  entrypoint:
    external: true

volumes:
  es01-data:
  es02-data:
  es03-data:
