---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana.ncserver.cloud
server.host: "0"
xpack.monitoring.ui.container.elasticsearch.enabled: true

xpack.reporting.kibanaServer.port: 443
xpack.reporting.kibanaServer.protocol: https
xpack.reporting.kibanaServer.hostname: kibana.ncserver.cloud

# elasticsearch.hosts: [ "http://es01:9200" ]
